[package]
name = "razor_engine_rust"
version = "0.1.0"
authors = ["Dmitry <mamhigtt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.21.0"
ash = "0.29.0"
